### ISSUE TITLE
env/configure is slow

### ISSUE THREAD

**Issue by arkadijs** [agilestacks/hub-extensions#8]
`hub configure` on already configured stack is slow in `env` extension. As I have about 10 files in HUB_FILES, and about 20 fromEnv-s it takes a long time to loop through each file individually with yq and jq:

```
yq
++ for f in '$HUB_FILES'
++ test -f params/dev/images.yaml
+++ yq e params/dev/images.yaml -j
+++ jq -cr '[ .. | objects | select(.fromEnv=="COMPONENT_DEX_MICROSOFT_CLIENTID").empty | select(.) ] | first | select(.)'
++ result=
++ test -n ''
++ for f in '$HUB_FILES'
++ test -f params/dev/external-images.yaml
+++ yq e params/dev/external-images.yaml -j
+++ jq -cr '[ .. | objects | select(.fromEnv=="COMPONENT_DEX_MICROSOFT_CLIENTID").empty | select(.) ] | first | select(.)'
++ result=
++ test -n ''
++ for f in '$HUB_FILES'
++ test -f params/dev/external-database.yaml
+++ yq e params/dev/external-database.yaml -j
+++ jq -cr '[ .. | objects | select(.fromEnv=="COMPONENT_DEX_MICROSOFT_CLIENTID").empty | select(.) ] | first | select(.)'
++ result=
++ test -n ''
++ for f in '$HUB_FILES'
++ test -f params/dev/dual-ingress.yaml
+++ yq e params/dev/dual-ingress.yaml -j
+++ jq -cr '[ .. | objects | select(.fromEnv=="COMPONENT_DEX_MICROSOFT_CLIENTID").empty | select(.) ] | first | select(.)'
++ result=
++ test -n ''
++ for f in '$HUB_FILES'
++ test -f params/prod/params.yaml
+++ yq e params/prod/params.yaml -j
```

**Comment by akranga** [comment]
This is a side effect from the bash script that relies on jq/yq expressions... The epxressions itself are recursive, because fromEnv can appear at the different places. IMHO there is no point to optimize even more complicated queries. Logically is to rewrite extension with general purpose language.

**Comment by akranga** [comment]
Another option could be to do an `elaborate`. THis however  will break the lifecycle: `configure` >> `elaborate` >> `deploy`, when `configure` is predicated to `elaborate`. 

Or write kinda elaborate that won't brake lifecycle but only will do performance optimisation, that sounds like an over-engineering. because only will work with extreme cases like too many hub files

**Comment by arkadijs** [comment]
In another place with similar slowdown, I just let yq process all HUB_FILES in a single invocation.

**Comment by akranga** [comment]
Makes sense, care to apply the change for `HUB_FILES`? I still for rewrite such functionality using regular progreamming language (statically typed)... Slowest point is actually recursive expressinon `..`.

Yet there is anotether slow point because we need to reconstruct param name, default values and desription retrospectively. 

Curretnly `env` is complex enough for the shell script

**Comment by akranga** [comment]
Fixed previously! Problem was in the obsolete Kubernetes call... to fetch state from there. If cluster is not available then there is a performance hit. 

For now hub show won't have obsolete call if there is no Kubernetes cluster. Newer version of YQ allows to better chain HUB_FILES as well
